project:
  type: website
  output-dir: _site
  resources:
    - "configs/**"
    - "workflow/**"
    - "env/**"
    - "scripts/bcfngs"

execute:
  enabled: false
editor: source
date: last-modified
format:
  html:
    theme: flatly
    highlight-style: textmate
    grid:
      body-width: 1425px
      margin-width: 290px
      gutter-width: 2rem
    css: styles.css
    toc: true
    toc-title: Content
    toc-depth: 2
    toc-expand: 2
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-newwindow: true

website:
  title: "Bioinformatics Core Facility MPI Biochemistry"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "environment"
        menu:
          - text: "micromamba + bcfngs"
            href: environment.html
          - text: "conda"
            href: conda.html
          - text: "snakemake"
            href: snakemake.html
      - text: "Updating genomes"
        href: updating_genomes.html
      - text: "Mapping"
        href: mapping.html
    right:
      - icon: github
        href: https://github.com/yeroslaviz
      - icon: bluesky
        href: https://bsky.app/profile/frymor
      - icon: globe
        href: https://www.biochem.mpg.de/en
      - icon: linkedin
        href: https://www.linkedin.com/in/ayeroslaviz/
        aria-label: LinkedIn
