# Get the appropriate genome for the analysis from the Ensembl FTP server.
# To get the correct data copy-paste the link for the fastA and gtf files in the correct row.

organism:
  "Dmel"
#  "Dpse"

fastA:
####### D. mel
  "ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.22.dna.toplevel.fa.gz"
####### D. pse
#  "ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_pseudoobscura/dna/Drosophila_pseudoobscura.Dpse_3.0.dna.toplevel.fa.gz"

gtf:
####### D. mel
  "ftp://ftp.ensembl.org/pub/current_gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.22.98.gtf.gz"
####### D. pse
#  "ftp://ftp.ensemblgenomes.org/pub/current/metazoa/gtf/drosophila_pseudoobscura/Drosophila_pseudoobscura.Dpse_3.0.45.gtf.gz"

#organism:
#  Dmel:
#    fastA: "ftp://ftp.ensembl.org/pub/current_fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.22.dna.toplevel.fa.gz"
#    gtf: "ftp://ftp.ensembl.org/pub/current_gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.22.98.gtf.gz"
#  Dpse:
#    fastA: "ftp://ftp.ensemblgenomes.org/pub/current/metazoa/fasta/drosophila_pseudoobscura/dna/Drosophila_pseudoobscura.Dpse_3.0.dna.toplevel.fa.gz"
#    gtf: "ftp://ftp.ensemblgenomes.org/pub/current/metazoa/gtf/drosophila_pseudoobscura/Drosophila_pseudoobscura.Dpse_3.0.45.gtf.gz"


##############STAR
## parameters for STAR indexing
RAM:
  141278166400 #  set maximum available RAM (bytes) for genome generation
SAindex:
  13 # For small genomes, the parameter --genomeSAindexNbases needs to be scaled down (default is 14).
## Is your library stranded? options are [true, false]
stranded: false
## Are the input files compressed [true, false]
gzipped: true

##############STAR
## parameters for bwa indexing
blockSize: 
  10000000000 # block size for the bwtsw algorithm, higher values relative to genoem size increases indexing process.

###############FeatureCounts
# how many threads:
FeatureCounts:
  threads: 5
