name: P135
channels:
   - bioconda
   - conda-forge
   - r
   - bioinfo
dependencies:
   - snakemake-minimal =5.2.4
   - python =3.6
   - star =2.7.2c
   - samtools =1.9
   - bedtools =2.29.0
   - subread =1.6.4
   - fastqc =0.11.8
   - sambamba =0.7.0
   - rseqc =3.0.1
   - bowtie2 =2.3.5
   - bwa =0.7.17

