---
title: "HOWTO"
author: "AY"
date: "2026-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a short internal HOW-TO for the bcfngs mapping automation.

## 1) Prepare environment

```bash
./scripts/bcfngs env create
./scripts/bcfngs env check
```

<<<<<<< Updated upstream
4. run the command `snakemake -nps archive/legacy/getGenome_IndexGenome.Snakefile` to check that the new genome is added to the workflow (the `-n` is a dry-run which just output the command without performing the tasks.)
5. run the same command without the `-n` - `snakemake -ps archive/legacy/getGenome_IndexGenome.Snakefile -j 12`. This will download the fastA and gtf files from the given links and create the index files for them as well. The parameter `-j` sets the number pf cores used in the snakemake run. If the number of cores is smaller then the one sets for e.g. STAR, only this numner of cores will be used. 


## Mapping

Mapping will be done with the `STAR` aligner for a specific genome either in a paired-end or single-end format. 

### Changing parameters before mapping

The following setting must be adjusted before running the script:
=======
## 2) Build or update genomes/indices
>>>>>>> Stashed changes

```bash
./scripts/bcfngs genomes plan
./scripts/bcfngs genomes build --cores 20
```

Subset build:

```bash
./scripts/bcfngs genomes build --cores 20 --organism Homo_sapiens,Mus_musculus
```

## 3) Configure mapping run

Edit `configs/run.yaml`:

```yaml
project: "P152"
path: "/fs/pool/pool-bcfngs/fastq_files/P152/conc.fastq/"
outdir: "/fs/pool/pool-bcfngs/mapping"
organism: "Drosophila_melanogaster"
threads: 16
ram_bytes: 168632718037
```

## 4) Run mapping

Dry-run:

```bash
./scripts/bcfngs mapping plan
```

Execute:

```bash
./scripts/bcfngs mapping run
```

Examples:

<<<<<<< Updated upstream
=======
```bash
# select mapper(s)
./scripts/bcfngs mapping run --mapper star,bwa,bowtie2

# single-end mode
./scripts/bcfngs mapping run --single-end

# keep intermediary files
./scripts/bcfngs mapping run --keep-intermediary-files
```

## 5) Run mapping on SLURM

```bash
./scripts/bcfngs mapping plan --executor slurm --jobs 20
./scripts/bcfngs mapping run  --executor slurm --jobs 20
```
>>>>>>> Stashed changes
