---
title: "Genome update and mapping workflow"
author: "Assa Yeroslaviz"
---

# Overview 

This project contains a conda-snakemake workflow for the mapping of the concatenated fastq file sequenced at the NGS facility of the MPIB.

The following documentation was meant for the sequencing center to help them run a preliminary analysis on the sequenced samples.

Following steps will be cover in this documentation

1. Instruction on how to create the conda environment with the needed tools for the mapping and genomic indices updates
2. The snakemake workflow for updating the genomic indices needed for the mapping
3. Automation of themapping procedure using different mapping tools (Some _tools_ are not yet incorporated in the workflow):
  - [STAR](https://github.com/alexdobin/STAR)
  - [bowtie2](https://github.com/BenLangmead/bowtie2)
  - [bwa](https://github.com/lh3/BWA)
  - [_kallisto_](https://kallisto.readthedocs.io/en/latest/)
  - [_salmon_](https://combine-lab.github.io/salmon/)
  - [_cellranger_](https://www.10xgenomics.com/support/software/cell-ranger/latest)

# Analysis steps

This tool is straightforward to use.

First, one must first install the conda environment. Instruction for this step can be found in the [environment file](environment.qmd).

Updating the genomic indices should be done once, only when a new genome build is published. Ourwirkflow is using the Ensembl genomes fro various organisms. More can be added as needed. 
The list of genomes included in this project can be found in the [genomes config file](configs/genomes.yaml). At the top of this file one can also see the actulal version of the [public repository](https://ftp.ensembl.org/pub/?C=M;O=D). 

We prepared a script called [`bcfngs`](scripts/bcfngs). This script can take three global paraemters for each of the three steps assigned in this project

```bash
$ ./scripts/bcfngs --help
usage: bcfngs [-h] [--profile {micromamba,modules}] [--env-prefix ENV_PREFIX] {env,genomes,mapping} ...

positional arguments:
  {env,genomes,mapping}

options:
  -h, --help            show this help message and exit
  --profile {micromamba,modules}
  --env-prefix ENV_PREFIX
                        Micromamba environment prefix (default: cluster env if present, else .mamba/env).
```

The first parameter, `bcfngs env` take care of creating and maintaining the environent. 

```bash
$ ./scripts/bcfngs env  --help
usage: bcfngs env [-h] {create,update,check} ...

positional arguments:
  {create,update,check}

options:
  -h, --help            show this help message and exit
```


## Preparing the genomeic indicies

For the genomic indices we need the chromosome sequences as fastA file as well as the genomic features in a gtf format. The `bcfngs genomes` script can download the genomes list in the aforementioned file and create the indicies for the tool listed above. 

A more elaborate instruction on how to run this step can be found in the [Updating genomes](updating_genomes.qmd) files. 

```bash
$ ./scripts/bcfngs genomes --help
usage: bcfngs genomes [-h] {check-updates,plan,build} ...

positional arguments:
  {check-updates,plan,build}

options:
  -h, --help            show this help message and exit
```

## Mapping step

After we nesured, that our needed genomic indices are available for the tool we would like to use, we can as easily run the mapping step for the proper tool using the sam `bcfngs mapping` command

```bash
$ ./scripts/bcfngs mapping --help
usage: bcfngs mapping [-h] {plan,run} ...

positional arguments:
  {plan,run}

options:
  -h, --help  show this help message and exit
```

More elaborate instructions as to how to use this script for mapping the genomes with your favorite tool can be found in the [mapping](mapping.qmd) file.

## Folder structure

To set the path were the genomes can be downloaded to use the genome config file. In our project we're taking advantage of the pool-folders structire of our institute and store all genomic indices in the pool folder of the ngs core facility (`pool-bcfngs`). 

```bash
genomes_root: /fs/pool/pool-bcfngs/genomes
```

Downloading the genomes creates a specific directory per organism, as can be seen below. The folder is split into the separate tools, also keeping the version of the tool that was used. To assertain reproducibility, we can keep previous version of genomics indices, using a softlink to point to the latest version of the indices. 


```bash
$ tree -L 3 Mus_musculus/
Mus_musculus/
├── bowtie2Index -> .../Mus_musculus/bowtie2Index-2.5.4
├── bowtie2Index-2.5.4
│   ├── Mus_musculus.1.bt2
│   ├── Mus_musculus.2.bt2
...
│   └── Mus_musculus.rev.2.bt2
├── bwaIndex -> .../genomes/Mus_musculus/bwaIndex-0.7.18
├── bwaIndex-0.7.18
│   ├── Mus_musculus.amb
...
│   └── Mus_musculus.sa
├── starIndex -> .../genomes/Mus_musculus/starIndex-2.7.11b
└── starIndex-2.7.11b
    ├── chrLength.txt
    ├── chrNameLength.txt
...
    ├── sjdbList.out.tab
    └── transcriptInfo.tab
```

# The Workflow

The workflow uses a **micromamba** environment with the `snakemake` tool (based on python). The advantage of micromamba is having an isolated environment, separated from the rest of the tools installed on the system. This gives better control over the tool versions used in the workflow, with fewer conflicts from older system installations. To learn more about micromamba, take a look at the [mamba documentation](https://mamba.readthedocs.io/en/latest/).

`snakemake` offers a lot of advantages as well. It allows better controls over different steps of the analysis, easier automation of the workflow and reduced running time through parallelization of the steps, just to mention some of them. to learn more about `snakemake` take a look at [the snakemake doc site](https://snakemake.readthedocs.io/en/stable/index.html).

- [environment](environment.qmd)
- [snakemake](snakemake.qmd)

# TO DO

Below we list both the organisms and the tools used in this workflow

1. ~~human~~
2. ~~mouse~~
3. ~~zebra fish~~
4. ~~fruit fly~~
5. ~~yeast~~
6. ~~worm (C. elegans)~~
7. ~~Chicken~~
8.

as well as which mappers we need

1. ~~star~~
2. ~~bwa~~
3. ~~bowtie2~~
4. kallisto
5. salmon
6. cellranger
7. hisat2

# CHANGES

### 06.03.2026

- Continued the Quarto migration and switched the remaining main pages from `.Rmd` to `.qmd`.
- Reworked and expanded the documentation pages:
  - [`index.qmd`](index.qmd)
  - [`environment.qmd`](environment.qmd)
  - [`snakemake.qmd`](snakemake.qmd)
  - [`updating_genomes.qmd`](updating_genomes.qmd)
  - [`mapping.qmd`](mapping.qmd)
- Updated the docs to match the current [`scripts/bcfngs`](scripts/bcfngs) wrapper and the latest published workflow resources.
- Restructured the "Updating genomes" documentation and added more explanatory notes across the site.

### 05.03.2026

- Reworked the homepage content and refreshed the published documentation structure.
- Updated the rendered workflow resources shipped with the site, including:
  - [`docs/configs/genomes.yaml`](docs/configs/genomes.yaml)
  - [`docs/configs/run.yaml`](docs/configs/run.yaml)
  - [`docs/env/environment.yml`](docs/env/environment.yml)
  - [`docs/workflow/genomes.smk`](docs/workflow/genomes.smk)
  - [`docs/workflow/mapping.smk`](docs/workflow/mapping.smk)
  - [`docs/scripts/bcfngs`](docs/scripts/bcfngs)

### 04.03.2026

- Added and published major documentation updates for:
  - [`mapping.qmd`](mapping.qmd)
  - [`snakemake.qmd`](snakemake.qmd)
  - [`updating_genomes.qmd`](updating_genomes.qmd)
- Refreshed the published Quarto site after multiple docs-source updates and site rebuilds.

### 27.02.2026

- Refreshed the published site files and synchronized bundled workflow resources in the documentation output.
- Updated the environment-related docs/output to use the correct `update_genomes` environment naming.

### 26.02.2026

- Published the Quarto site from the `docs/` output directory for GitHub Pages.
- Updated the environment instructions to reflect the correct micromamba / miniconda environment path.
- Added sanity-check output examples to the environment documentation.
- Cleaned up legacy repository artifacts related to the old docs/site layout.

### 20.02.2026

- Added Quarto website configuration (`_quarto.yml`) and re-rendered site with `quarto render`.
- Updated navbar:
  - Added links to [`environment`](environment.html), [`snakemake`](snakemake.html), and [`Updating genomes`](updating_genomes.html).
  - Replaced the old contact page with an email link: <mailto:yeroslaviz@biochem.mpg.de>.
  - Removed Twitter and added Bluesky.
- Converted `scripts/Updating_genomes.txt` into [`updating_genomes.qmd`](updating_genomes.qmd) (and removed the original text file).
- Switched environment management docs from conda to micromamba:
  - Added [`environment.qmd`](environment.qmd) and [`env/environment.yml`](env/environment.yml).
  - Added cookbook-style “how-to” instructions for common scenarios (new installs, updates, HPC module fallback).
- Added a new “one command” wrapper CLI: [`scripts/bcfngs`](scripts/bcfngs) (preflight checks, lint, dry-run, then run).
- Added new Snakemake configuration + workflow for genome download and indexing:
  - [`configs/genomes.yaml`](configs/genomes.yaml) (scientific organism IDs, pinned releases, index versioning)
  - [`configs/run.yaml`](configs/run.yaml) (per-project mapping settings)
  - [`workflow/genomes.smk`](workflow/genomes.smk) (downloads FASTA/GTF, builds STAR+bwa+bowtie2 indices, updates symlinks, creates chromSize)
- Updated the STAR mapping Snakefiles to use `configs/run.yaml` and scientific organism IDs.


### 27.06.2022

new genome built were added to the workflow

- _D. melanogaster_ - `BDGP6.28`
- _E. coli_ - `HUSEC2011CHR1`
- _D. pseudoobscura_ - `3.0.49`
- _C. elegans_ - `WBcel 2.35`

### 13.01.2020

- a short [`HOWTO`](HOWTO.html) was added. This serves as a fast introduction, if `conda` and `snakemake` are already installed and set for the mapping.
- the genome of _D. pseudoobscura_ was added to the `config.yaml` file.

### 11.12.2019

The workflow now should work on the hpcl cluster of the MPI. For that reason some changes were made to the folder structure and the depth of the analysis

1. the mappers `bowtie2` and `bwa` were removed from the analysis. It will done from now on only with `STAR`.
2. the working directory of the analysis should be the `conc.fastq` folder in the pool-bcfngs pool folder of the Sequencing core facility.
3. The workflow will create a new folder with the structure `ProjectNumber/Organism/` were it will save two new folders for the star mapping results and the bigwig files.
4. the first script to get the genomes should be only run once, or when the genome version must be updated.
5. The second script was splitted into single-end and paired-end version and should be run accordingly.
