import os

# Mapping file for single-end STAR mapping.
############
# Uses configs/run.yaml (resolved relative to this Snakefile).
configfile: os.path.join(workflow.basedir, "configs/run.yaml")

gz_command = "--readFilesCommand zcat" if config.get("gzipped", True) else ""

path = config["path"]
print("Directory of raw fastq reads:")
print(path)

# testing for reading in a list pf files from a specific folder:
IDS, = glob_wildcards("{sample}.conc.R1.fastq.gz")

print("Sample list:")
print(IDS)

project = config["project"]
organism = config.get("organism") or config.get("org")
if not organism:
    raise ValueError("Missing config key: organism")
print("Project Number is:" ,project)
print("Mapping against genome", organism)

threads = int(config.get("threads", 16))
ram_bytes = config.get("ram_bytes", config.get("RAM"))

rule all:
    input:
        expand("{project}/{organism}/star/{sample}.bam", sample=IDS, organism=organism, project=project),
        expand("{project}/{organism}/star/{sample}.bam.bai", sample=IDS, organism=organism, project=project),
        expand("{project}/{organism}/bwig/{sample}.bw", sample=IDS, organism=organism, project=project)

rule map_star:
    input:
        R1='{IDS}.conc.R1.fastq.gz'
    output:
        bam='{project}/{organism}/star/{IDS}.bam',
        counts="{project}/{organism}/star/{IDS}.counts.tab",
        SJ = "{project}/{organism}/star/{IDS}SJ.out.tab",
    benchmark:
        "{project}/{organism}/star/{IDS}.benchmarks.STAR.txt"
    params:
        prefix ="{project}/{organism}/star/{IDS}",
        gz_support=gz_command,
        index=f"/fs/pool/pool-bcfngs/genomes/{organism}/starIndex/",
        ram=ram_bytes
    threads: threads
    shell:
        r'''
	mkdir -p {params.prefix}
####### for paired-end reads samples data set
        STAR --runThreadN {threads} --genomeDir {params.index} --outFileNamePrefix {params.prefix} --readFilesIn {input.R1} {params.gz_support} --outSAMtype BAM SortedByCoordinate --limitBAMsortRAM {params.ram} --quantMode GeneCounts --outReadsUnmapped Fastx
        mv {params.prefix}Aligned.sortedByCoord.out.bam {output.bam}
        mv {params.prefix}ReadsPerGene.out.tab {output.counts}
        rmdir {params.prefix}
        '''


rule index:
    input:
        '{project}/{organism}/star/{IDS}.bam'
    output:
        '{project}/{organism}/star/{IDS}.bam.bai'
    shell:
        'samtools index {input}'

#
# chromSize files are generated by the genome workflow under:
# /fs/pool/pool-bcfngs/genomes/<Organism>.chromSize
#

rule create_bigwig:
    input:
        chromSize = "/fs/pool/pool-bcfngs/genomes/{organism}.chromSize",
        bam = "{project}/{organism}/star/{IDS}.bam",
        bai = "{project}/{organism}/star/{IDS}.bam.bai"
    output:
        bw = "{project}/{organism}/bwig/{IDS}.bw"
    params:
        dir ="{project}/{organism}/bwig",
        prefix ="{project}/{organism}/bwig/{IDS}",
        wig = "{project}/{organism}/bwig/{IDS}.wig"
    shell:
        """
        mkdir -p {params.dir}
        bam2wig.py  -i {input.bam} -s {input.chromSize} -o {params.prefix} &> {params.prefix}.log
        rm {params.wig}
        """
