name: bcfngs-mapping
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - snakemake >=8,<9
  - pyyaml
  - star
  - bwa
  - bowtie2
  - samtools
  - bedtools
  - rseqc
  - ucsc-wigtobigwig
  - curl
  - wget

